### ISSUE TITLE
install locally rather than in /usr/local/bin (example for DESTDIR needed)

### ISSUE THREAD

**Issue by chiarcos** [santhoshtr/sfst#26]
I am trying to build sfst in the local workspace of the current user, Ubuntu 22.04 LTS.[1] For this, I would ask you for an example of setting `DESTDIR` in accordance with the line "Change the variable DESTDIR in Makefile if you want to install to a different directory." from the Readme.

My naive interpretation was that this means to run the following sequence of commands:

    $> git clone https://github.com/santhoshtr/sfst.git;
    $> cd sfst;
    $> mkdir build;
    $> cd build;
    $> cmake ..;
    $> make DESTDIR=~/tmp;
    $> make install DESTDIR=~/tmp;
    $> cd ../..;

Which, however, yields

    Install the project...
    -- Install configuration: ""
    ...
    -- Installing: /home/christian/tmp/usr/local/include/utf8.h
    CMake Error at src/cmake_install.cmake:65 (file):
      file INSTALL cannot find
      "/home/christian/Desktop/github/nmk-corpus/scripts/sfst/build/src/fst-compiler.h":
      No such file or directory.
    Call Stack (most recent call first):
      cmake_install.cmake:47 (include)
    
    make[1]: *** [Makefile:120: install] Error 1

I guess this is has a rather obvious solution, apologies for the stupid question.

[1] I need to install somewhere in the user space, because without setting `DESTDIR`, I get the expected permission denied error, and on the machine I want to run it on, I don't have `sudo` rights.

    ...
    Install the project...
    -- Install configuration: ""
    -- Installing: /usr/local/lib/libsfst.so
    CMake Error at src/cmake_install.cmake:52 (file):
      file INSTALL cannot copy file
      "/home/christian/Desktop/github/nmk-corpus/scripts/sfst/build/src/libsfst.so"
      to "/usr/local/lib/libsfst.so": Permission denied.
    Call Stack (most recent call first):
      cmake_install.cmake:47 (include)

PS: I tried different kinds of DESTDIR paths, both absolute and relative. I also tried using the DESTDIR flag on `make install` only rather than on both that and the earlier call to `make`. No difference.

**Comment by chiarcos** [comment]
Looking at the log again, it actually seems that the `DESTDIR=...` flag worked correctly, as it produced `/home/christian/tmp/usr/local/include/utf8.h`. So I guess the error is somewhere else.

**Comment by chiarcos** [comment]
As it turned out, the original error was due to missing dependencies. However, that wasn't sufficiently obvious from the log nor the final error message. Still not compiling, but the errors are different by now. As for this issue, I suggest to add the example with `DESTDIR=...` to the readme and then, to close the issue.

**Comment by santhoshtr** [comment]
Updated the documentation as requested. Thanks!
