### ISSUE TITLE
Sources of manual and tutorial

### ISSUE THREAD

**Issue by asdofindia** [santhoshtr/sfst#27]
While packaging for debian it came up that the PDFs in the doc folder might be binaries with copyright issue.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991815#30

It is also useful to have the source TeX files of these to be able to update these manuals.

Can the source be located and added within?

**Comment by santhoshtr** [comment]
I do not have the source for these PDFs. The [previous upstream](https://www.cis.lmu.de/~schmid/tools/SFST/) also does not have them. Also, not present in http://packages.debian.org/sid/sfst. 

I will email Helmut Schmid, original author if they have the source.
