### ISSUE TITLE
Header files can conflict with other packages

### ISSUE THREAD

**Issue by asdofindia** [santhoshtr/sfst#31]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079107

> libsfst-dev: /usr/include/utf8.h is already provided by libutfcpp-dev

They're suggesting if sfst headers can be namespaced into a subfolder. I'm not sure if this can be achieved through some cmake config or whether it needs the source directory to be reorganized

**Comment by santhoshtr** [comment]
Thanks @anoopmsivadas for the patch. Merged, and released new version https://github.com/santhoshtr/sfst/releases/tag/1.7.0
